name: mally
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  http: ^0.13.6
  dio: ^5.3.3
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  path: ^1.8.0
  path_provider: ^2.0.15
  image_gallery_saver: ^2.0.1
  gallery_saver: ^2.3.2
  permission_handler: ^11.3.0
  flutter_barcode_scanner: ^2.0.0
  url_launcher: ^6.1.11
  flutter_xlider: ^3.5.0
  assets_audio_player: ^3.0.4+3
  syncfusion_flutter_sliders: ^24.2.7
  image_picker: ^1.0.7
  image: ^4.1.7
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  intl: ^0.19.0
  http_parser: ^4.0.2
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  flutter_sound: 9.2.13

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^3.0.1
  dart_code_linter: ^1.1.1

flutter: 
  uses-material-design: true
  assets: 
    - music/
    - assets/
    - assets/images/
    - assets/categories/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
